# Generated by Django 4.0.4 on 2022-04-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='describtion',
            new_name='description',
        ),
    ]
