# Generated by Django 4.0.4 on 2022-04-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_rename_describtion_hotel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotelImge',
            new_name='hotelImage',
        ),
    ]
