# Generated by Django 4.0.4 on 2022-04-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_rename_hotelimge_hotel_hotelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='bed_quantity',
        ),
    ]
