# Generated by Django 4.0.4 on 2022-04-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_remove_hotel_bed_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotelName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
