# Generated by Django 4.0.4 on 2022-04-21 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_remove_hotel_region_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image1', models.ImageField(blank=True, upload_to='hotels/rooms')),
                ('room_image2', models.ImageField(blank=True, upload_to='hotels/rooms')),
                ('room_image3', models.ImageField(blank=True, upload_to='hotels/rooms')),
                ('room_image4', models.ImageField(blank=True, upload_to='hotels/rooms')),
                ('room_mass', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('floor', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('beds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('bathroom', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('kitchen', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('balcony', models.BooleanField(default=False)),
                ('fire_extinguisher', models.BooleanField(default=False)),
                ('minibar', models.BooleanField(default=False)),
                ('telephone', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
    ]
