# Generated by Django 4.0.4 on 2022-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_remove_hotel_price_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tp',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Vip'), (3, 'Deluxe')], default=1),
        ),
    ]
