# Generated by Django 4.0.4 on 2022-04-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_room_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
