# Generated by Django 4.0.4 on 2022-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_room_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image1',
            field=models.ImageField(blank=True, default='hotels/photos/no-image.png', upload_to='hotels/rooms'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image2',
            field=models.ImageField(blank=True, default='hotels/photos/no-image.png', upload_to='hotels/rooms'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image3',
            field=models.ImageField(blank=True, default='hotels/photos/no-image.png', upload_to='hotels/rooms'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image4',
            field=models.ImageField(blank=True, default='hotels/photos/no-image.png', upload_to='hotels/rooms'),
        ),
    ]
