# Generated by Django 4.0.4 on 2022-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_alter_room_bathroom_alter_room_beds_alter_room_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image2',
            field=models.ImageField(blank=True, upload_to='hotels/rooms'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image3',
            field=models.ImageField(blank=True, upload_to='hotels/rooms'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image4',
            field=models.ImageField(blank=True, upload_to='hotels/rooms'),
        ),
    ]
